### ISSUE TITLE
Instructions how to set this up?

### ISSUE THREAD

**Issue by danielkrajnik** [flocks/elfeed-notifier#1]
Sorry, I'm new to emacs, what do you need to add to config.el to get this to work?

**Comment by slackline** [comment]
@danielkrajnik Emacs loads its configuration from an [init.el](https://www.emacswiki.org/emacs/InitFile) when it starts.

You need a copy of `elfeed-notifier.el` locally on your computer and then in your `init.el` you could add the following...

```bash
(load "~/path/to/elfeed-notifier.el")
```

**Comment by danielkrajnik** [comment]
Thanks, it may be a but more complicated than that though when you are on doom emacs and what eventually seemed to work (elfeed updates automatically with a timer) was adding this macro to config.el:

```elisp
(use-package! elfeed-system-notifier
  :defer t
  :commands elfeed-notifier-mode)
(elfeed-notifier-mode)
``` 

to get the package it needed to be added like this (it uses straight.el package manager) (`packages.el`):
```elisp
(package! elfeed-system-notifier
  :recipe (:host github :repo "danielkrajnik/elfeed-system-notifier"))

```

I was confused, because it required invoking the commands `elfeed-notifier-mode` and `elfeed-notifier-mode` from use-package! macro.

I assume that this isn't an intended behavior? It should have Just Worked after loading the `elfeed-notifier.el` file right?

**Comment by flocks** [comment]
Hello @danielkrajnik,

This is how I personally use the package
```elisp
(use-package elfeed-notifier
  :straight (elfeed-notifier :type git :host github :repo "flocks/elfeed-notifier")
  :config
  (elfeed-notifier-mode))
```
> I assume that this isn't an intended behavior? It should have Just Worked after loading the elfeed-notifier.el file right?

Honestly I don't know, it seems a common pattern to let the user activate/deactivate the mode

**Comment by danielkrajnik** [comment]
Perfect, thank you. I didn't know that it was necessary to evaluate the `elfeed-notifier-mode` after loading. It makes sense now.

**Comment by flocks** [comment]
I'm glad you finally managed to set it up
